In [ ]:
import torch
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))

True
NVIDIA GeForce RTX 4060 Laptop GPU

In [ ]:
import pandas as pd
import numpy as np
import torch.nn as nn
from sklearn.preprocessing import MinMaxScaler

In [ ]:
df=pd.read_csv("nifty_10yrs.csv")
print("FIRST 5 VALUES")
df.head()

FIRST 5 VALUES

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Company
0,2013-12-30 00:00:00+05:30,38.666786,38.695041,37.331744,37.614292,5612941,0.0,0.0,ADANIENT
1,2013-12-30 00:00:00+05:30,1593.923342,1593.923342,1553.678139,1564.609375,168075,0.0,0.0,HEROMOTOCO
2,2013-12-30 00:00:00+05:30,314.647645,314.740632,309.231520,311.253845,2113802,0.0,0.0,HDFCBANK
3,2013-12-30 00:00:00+05:30,248.808099,250.981959,243.887267,246.377319,1578700,0.0,0.0,HCLTECH
4,2013-12-30 00:00:00+05:30,397.459083,399.023178,392.174721,394.696289,241807,0.0,0.0,GRASIM

In [ ]:
print("BASIC STAT OF DATA")
df.describe()

BASIC STAT OF DATA

,Open,High,Low,Close,Volume,Dividends,Stock Splits
count,120842.000000,120842.000000,120842.000000,120842.000000,1.208420e+05,120842.000000,120842.000000
mean,1437.633608,1454.109653,1419.667244,1436.523545,7.279751e+06,0.073408,0.000900
std,2253.773717,2276.028154,2229.055748,2252.267257,1.789070e+07,1.882754,0.070707
min,15.739931,15.870457,15.332995,15.463521,0.000000e+00,0.000000,0.000000
25%,301.550153,305.647502,296.746537,301.138649,8.705430e+05,0.000000,0.000000
50%,679.015380,687.878745,670.507797,678.983673,2.637864e+06,0.000000,0.000000
75%,1653.873064,1674.674071,1632.166414,1652.880646,6.934536e+06,0.000000,0.000000
max,26250.000000,26650.000000,26145.650391,26580.300781,6.428460e+08,180.000000,10.000000

In [ ]:
print("MISSING VALUES")
df.isnull().sum()

MISSING VALUES

Date            0
Open            0
High            0
Low             0
Close           0
Volume          0
Dividends       0
Stock Splits    0
Company         0
dtype: int64

In [ ]:
print("COLUMNS OF DATASET")
df.columns

COLUMNS OF DATASET

Index(['Date', 'Open', 'High', 'Low', 'Close', 'Volume', 'Dividends',
       'Stock Splits', 'Company'],
      dtype='object')

In [ ]:
print("UNIQUE_COMPANIES")
companies=df['Company'].unique()

print("Total Companies",len(companies))
print(companies[:10])

UNIQUE_COMPANIES
Total Companies 50
['ADANIENT' 'HEROMOTOCO' 'HDFCBANK' 'HCLTECH' 'GRASIM' 'EICHERMOT' 'UPL'
 'DRREDDY' 'DIVISLAB' 'COALINDIA']

In [ ]:
for company in companies:
    company_df=df[df['Company']==company]

    print(company,company_df.shape)

ADANIENT (2467, 9)
HEROMOTOCO (2467, 9)
HDFCBANK (2467, 9)
HCLTECH (2467, 9)
GRASIM (2467, 9)
EICHERMOT (2467, 9)
UPL (2467, 9)
DRREDDY (2467, 9)
DIVISLAB (2467, 9)
COALINDIA (2467, 9)
CIPLA (2467, 9)
BRITANNIA (2467, 9)
BPCL (2467, 9)
BHARTIARTL (2467, 9)
WIPRO (2467, 9)
BAJFINANCE (2467, 9)
BAJAJ-AUTO (2467, 9)
BAJAJFINSV (2467, 9)
AXISBANK (2467, 9)
ASIANPAINT (2467, 9)
HINDALCO (2467, 9)
ULTRACEMCO (2467, 9)
HINDUNILVR (2467, 9)
ICICIBANK (2467, 9)
TATASTEEL (2467, 9)
TATAMOTORS (2467, 9)
TATACONSUM (2467, 9)
SUNPHARMA (2467, 9)
SBIN (2467, 9)
RELIANCE (2467, 9)
TECHM (2467, 9)
POWERGRID (2467, 9)
ONGC (2467, 9)
APOLLOHOSP (2467, 9)
NTPC (2467, 9)
M&M (2467, 9)
MARUTI (2467, 9)
TITAN (2467, 9)
LT (2467, 9)
KOTAKBANK (2467, 9)
JSWSTEEL (2467, 9)
ITC (2467, 9)
INFY (2467, 9)
INDUSINDBK (2467, 9)
NESTLEIND (2467, 9)
ADANIPORTS (2467, 9)
TCS (2467, 9)
LTIM (1839, 9)
SBILIFE (1543, 9)
HDFCLIFE (1511, 9)

In [ ]:
def create_sequence(data,seq_length=60):
    x,y=[],[]
    for i in range(len(data) - seq_length):
        x.append(data[i:i+seq_length])
        y.append(data[i+seq_length])
    return np.array(x),np.array(y)

In [ ]:
scalers = {}

features = ['Open', 'High', 'Low', 'Close', 'Volume']
all_x = []
all_y = []

for company in companies:
    company_df = df[df['Company'] == company]
    company_df = company_df.sort_values(by='Date')

    data = company_df[features].values

    scaler = MinMaxScaler()
    data = scaler.fit_transform(data)

    scalers[company] = scaler   # 🔥 IMPORTANT

    x, y = create_sequence(data)

    if len(x) > 0:
        all_x.append(x)
        all_y.append(y[:, 3])

x_all = np.concatenate(all_x, axis=0)
y_all = np.concatenate(all_y, axis=0)

print("Final dataset shape:", x_all.shape)

Final dataset shape: (117842, 60, 5)

In [ ]:
split=int(0.8*len(x_all))

X_train=x_all[:split]
X_test=x_all[split:]
Y_train=y_all[:split]
Y_test=y_all[split:]

In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

X_train = torch.tensor(X_train, dtype=torch.float32).to(device)
y_train = torch.tensor(Y_train, dtype=torch.float32).unsqueeze(1).to(device)

X_test = torch.tensor(X_test, dtype=torch.float32).to(device)
y_test = torch.tensor(Y_test, dtype=torch.float32).unsqueeze(1).to(device)

print("Using device:", device)

Using device: cuda

In [ ]:
class LSTMModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.lstm = nn.LSTM(
            input_size=5,
            hidden_size=64,
            num_layers=2,
            batch_first=True,
            dropout=0.2  
        )
        self.fc = nn.Linear(64, 1)

    def forward(self, x):
        out, _ = self.lstm(x)
        out = out[:, -1, :]
        return self.fc(out)

model = LSTMModel().to(device)

In [ ]:
import time

# Metrics storage
train_losses = []
val_losses = []
epoch_times = []
r2_scores = []

# Function for R2 score (accuracy for regression)
def r2_score(y_true, y_pred):
    y_true = y_true.cpu().numpy()
    y_pred = y_pred.cpu().detach().numpy()
    
    ss_total = ((y_true - y_true.mean()) ** 2).sum()
    ss_res = ((y_true - y_pred) ** 2).sum()
    
    return 1 - (ss_res / ss_total)

In [ ]:
criterion = nn.MSELoss()

In [ ]:

optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

epochs = 50
batch_size = 64

for epoch in range(epochs):
    start_time = time.time()

    model.train()
    total_loss = 0

    for i in range(0, len(X_train), batch_size):
        X_batch = X_train[i:i+batch_size]
        y_batch = y_train[i:i+batch_size]

        optimizer.zero_grad()
        outputs = model(X_batch)
        loss = criterion(outputs, y_batch)

        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    train_loss = total_loss / (len(X_train) / batch_size)

    model.eval()
    with torch.no_grad():
        val_outputs = model(X_test)
        val_loss = criterion(val_outputs, y_test).item()

        r2 = r2_score(y_test, val_outputs)

    epoch_time = time.time() - start_time

    print(f"Epoch {epoch+1}/{epochs} | Time: {epoch_time:.2f}s | Train Loss: {train_loss:.4f} | Val Loss: {val_loss:.4f} | R2: {r2:.4f}")

Epoch 1/50 | Time: 3.06s | Train Loss: 0.0006 | Val Loss: 0.0102 | R2: 0.8632
Epoch 2/50 | Time: 2.60s | Train Loss: 0.0007 | Val Loss: 0.0158 | R2: 0.7885
Epoch 3/50 | Time: 2.62s | Train Loss: 0.0006 | Val Loss: 0.0027 | R2: 0.9637
Epoch 4/50 | Time: 2.63s | Train Loss: 0.0005 | Val Loss: 0.0091 | R2: 0.8775
Epoch 5/50 | Time: 2.69s | Train Loss: 0.0005 | Val Loss: 0.0040 | R2: 0.9463
Epoch 6/50 | Time: 2.73s | Train Loss: 0.0005 | Val Loss: 0.0098 | R2: 0.8679
Epoch 7/50 | Time: 2.78s | Train Loss: 0.0005 | Val Loss: 0.0005 | R2: 0.9930
Epoch 8/50 | Time: 2.75s | Train Loss: 0.0007 | Val Loss: 0.0003 | R2: 0.9966
Epoch 9/50 | Time: 2.70s | Train Loss: 0.0003 | Val Loss: 0.0006 | R2: 0.9922
Epoch 10/50 | Time: 2.78s | Train Loss: 0.0004 | Val Loss: 0.0031 | R2: 0.9585
Epoch 11/50 | Time: 2.73s | Train Loss: 0.0004 | Val Loss: 0.0005 | R2: 0.9936
Epoch 12/50 | Time: 2.68s | Train Loss: 0.0005 | Val Loss: 0.0004 | R2: 0.9951
Epoch 13/50 | Time: 2.71s | Train Loss: 0.0003 | Val Loss: 0.0006 | R2: 0.9916
Epoch 14/50 | Time: 2.67s | Train Loss: 0.0003 | Val Loss: 0.0004 | R2: 0.9950
Epoch 15/50 | Time: 2.85s | Train Loss: 0.0003 | Val Loss: 0.0006 | R2: 0.9918
Epoch 16/50 | Time: 2.74s | Train Loss: 0.0003 | Val Loss: 0.0013 | R2: 0.9824
Epoch 17/50 | Time: 2.63s | Train Loss: 0.0003 | Val Loss: 0.0002 | R2: 0.9970
Epoch 18/50 | Time: 2.76s | Train Loss: 0.0004 | Val Loss: 0.0035 | R2: 0.9531
Epoch 19/50 | Time: 2.70s | Train Loss: 0.0004 | Val Loss: 0.0005 | R2: 0.9927
Epoch 20/50 | Time: 2.64s | Train Loss: 0.0003 | Val Loss: 0.0004 | R2: 0.9940
Epoch 21/50 | Time: 2.61s | Train Loss: 0.0003 | Val Loss: 0.0004 | R2: 0.9948
Epoch 22/50 | Time: 2.59s | Train Loss: 0.0003 | Val Loss: 0.0004 | R2: 0.9949
Epoch 23/50 | Time: 2.60s | Train Loss: 0.0003 | Val Loss: 0.0003 | R2: 0.9963
Epoch 24/50 | Time: 2.60s | Train Loss: 0.0003 | Val Loss: 0.0002 | R2: 0.9973
Epoch 25/50 | Time: 2.60s | Train Loss: 0.0002 | Val Loss: 0.0003 | R2: 0.9966
Epoch 26/50 | Time: 2.62s | Train Loss: 0.0005 | Val Loss: 0.0014 | R2: 0.9813
Epoch 27/50 | Time: 2.59s | Train Loss: 0.0003 | Val Loss: 0.0003 | R2: 0.9964
Epoch 28/50 | Time: 2.57s | Train Loss: 0.0002 | Val Loss: 0.0005 | R2: 0.9928
Epoch 29/50 | Time: 2.62s | Train Loss: 0.0003 | Val Loss: 0.0002 | R2: 0.9973
Epoch 30/50 | Time: 2.63s | Train Loss: 0.0003 | Val Loss: 0.0004 | R2: 0.9951
Epoch 31/50 | Time: 2.64s | Train Loss: 0.0003 | Val Loss: 0.0003 | R2: 0.9960
Epoch 32/50 | Time: 2.57s | Train Loss: 0.0003 | Val Loss: 0.0002 | R2: 0.9969
Epoch 33/50 | Time: 2.59s | Train Loss: 0.0003 | Val Loss: 0.0004 | R2: 0.9950
Epoch 34/50 | Time: 2.62s | Train Loss: 0.0003 | Val Loss: 0.0002 | R2: 0.9967
Epoch 35/50 | Time: 2.60s | Train Loss: 0.0003 | Val Loss: 0.0005 | R2: 0.9936
Epoch 36/50 | Time: 2.62s | Train Loss: 0.0002 | Val Loss: 0.0003 | R2: 0.9957
Epoch 37/50 | Time: 2.62s | Train Loss: 0.0002 | Val Loss: 0.0006 | R2: 0.9922
Epoch 38/50 | Time: 2.59s | Train Loss: 0.0003 | Val Loss: 0.0004 | R2: 0.9947
Epoch 39/50 | Time: 2.58s | Train Loss: 0.0002 | Val Loss: 0.0003 | R2: 0.9956
Epoch 40/50 | Time: 2.60s | Train Loss: 0.0003 | Val Loss: 0.0004 | R2: 0.9947
Epoch 41/50 | Time: 4.90s | Train Loss: 0.0003 | Val Loss: 0.0003 | R2: 0.9954
Epoch 42/50 | Time: 6.58s | Train Loss: 0.0003 | Val Loss: 0.0004 | R2: 0.9951
Epoch 43/50 | Time: 6.37s | Train Loss: 0.0003 | Val Loss: 0.0003 | R2: 0.9959
Epoch 44/50 | Time: 6.18s | Train Loss: 0.0002 | Val Loss: 0.0003 | R2: 0.9965
Epoch 45/50 | Time: 6.20s | Train Loss: 0.0003 | Val Loss: 0.0004 | R2: 0.9944
Epoch 46/50 | Time: 6.19s | Train Loss: 0.0002 | Val Loss: 0.0003 | R2: 0.9965
Epoch 47/50 | Time: 6.43s | Train Loss: 0.0002 | Val Loss: 0.0005 | R2: 0.9936
Epoch 48/50 | Time: 4.87s | Train Loss: 0.0002 | Val Loss: 0.0003 | R2: 0.9963
Epoch 49/50 | Time: 2.74s | Train Loss: 0.0002 | Val Loss: 0.0002 | R2: 0.9974
Epoch 50/50 | Time: 3.01s | Train Loss: 0.0002 | Val Loss: 0.0002 | R2: 0.9974

In [ ]:
torch.save(model.state_dict(), "model.pth")

In [ ]:
model.load_state_dict(torch.load("model.pth"))
model.eval()

LSTMModel(
  (lstm): LSTM(5, 64, num_layers=2, batch_first=True, dropout=0.2)
  (fc): Linear(in_features=64, out_features=1, bias=True)
)

In [ ]:
with torch.no_grad():
    predictions = model(X_test)

predictions = predictions.cpu().numpy()
actual = y_test.cpu().numpy()

In [ ]:
real_predictions = []
real_actuals = []

for i in range(len(predictions)):
    # Create dummy array (5 features)
    dummy_pred = np.zeros((1,5))
    dummy_actual = np.zeros((1,5))
    
    # Put Close value at index 3
    dummy_pred[0,3] = predictions[i]
    dummy_actual[0,3] = actuals[i]
    
    # Inverse transform
    real_pred = scaler.inverse_transform(dummy_pred)[0,3]
    real_act = scaler.inverse_transform(dummy_actual)[0,3]
    
    real_predictions.append(real_pred)
    real_actuals.append(real_act)

In [ ]:
for i in range(10):
    print(f"Actual Market Closing: ₹{real_actuals[i]:.2f} | Predicted Market Closing: ₹{real_predictions[i]:.2f}")

Actual: ₹417.82 | Predicted: ₹414.91
Actual: ₹417.39 | Predicted: ₹416.78
Actual: ₹416.44 | Predicted: ₹417.20
Actual: ₹418.48 | Predicted: ₹417.48
Actual: ₹418.52 | Predicted: ₹418.42
Actual: ₹418.91 | Predicted: ₹419.19
Actual: ₹417.49 | Predicted: ₹419.83
Actual: ₹419.15 | Predicted: ₹419.16
Actual: ₹422.12 | Predicted: ₹419.60
Actual: ₹420.72 | Predicted: ₹421.44